apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
namePrefix: dev-
resources:
- ../../base
configMapGenerator:
- name: eshop-product-api-configmap
  behavior: merge
  files:
    - application.yml
