pipeline {
  agent any
  stages {
    stage('Checkout eshop project') {
      steps {
        git branch: 'main',
          credentialsId: '04b7fff3-441b-491a-9c6d-1654a7fd0b77',
          url: 'https://github.com/setnext/eshop-product.git'

        sh "ls -lat"
      }
    }
    stage('Build and Test') {
      steps {
        agent {
      	docker {
        	image 'maven:3.5.0'
        }
      }
      steps {
      	sh 'mvn clean install'
      }
      }
    }
    }
  }
