pipeline {
  
  agent none

  environment { 
   NAME = "eshop-product"
   GIT_COMMIT_REV=''
   VERSION = "${env.BUILD_ID}-${GIT_COMMIT}"
   IMAGE = "${NAME}:${VERSION}"
   REPONAME = "setnext"
  }
  stages {
    stage('Checkout eshop project') {
      agent any
      steps {
        script {
        def scmVars = checkout([$class: 'GitSCM',
         branches: [[name: '*/main']],
         userRemoteConfigs: [[credentialsId: 'my-username-password-id',
                             url: 'https://github.com/setnext/eshop-product.git']]])
        sh "ls -lat"
        echo "scmVars.GIT_COMMIT"
        echo "${scmVars.GIT_COMMIT}"
        GIT_COMMIT_REV=$(echo $scmVars.GIT_COMMIT| cut -d'_' -f 5)
      }
      }
    }
    stage('Build and Test') {
       agent {
        docker {
            image 'maven:3.8.1-openjdk-17' 
            args '-v /Users/nbabu/.m2:/root/.m2' 
        }
    }
      steps {
      	sh 'mvn -B -DskipTests clean package'
      }
    }
     stage('Docker Build') {
    	agent any
      steps {
         sh 'docker build --progress=plain --no-cache -t ${REPONAME}/${env.BUILD_ID}:${GIT_COMMIT_REV} .'
      }
    }
    }
  }
