management:
  endpoints:
    web:
      exposure:
        include: health,metrics
spring:
  data:
    mongodb:
      socketTimeout: '2000000'
      database: eshop
      uri: mongodb://eshop:muruga%40321@mongo.db.svc.cluster.local:27017/eshop
  servlet:
    multipart:
      max-request-size: 2048KBe
      max-file-size: 2048KB
logging:
  level:
    org:
      springframework: error
data:
  initialization:
    required: 'false'
server:
  port: '8080'
springdoc:
  swagger-ui:
    path: /swagger-ui.html
amazonProperties:
  accessKey: *
  secretKey: *
  region: us-east-1
  bucket: setnext-eshop
