apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api
resources:
- service.yaml
- deployment.yaml
configMapGenerator:
- files:
  - application.yml
  name: eshop-product-api-configmap
